background-image
js-tasks-ru/htmlcss-20220519_mivanova pull request #11
Opened 2022-06-07 06:10 UTC by MarMarIvanova

2022-06-07 06:10 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-06-07 06:15 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-06-07 17:56 UTC, GSemikozov requested changes

2022-06-07 17:56 UTC, GSemikozov commented on 06-lection4/02-background-image/background-image.css
> +  @media (min-width: 768px) {
размер аватара не меняется, соответственно нет смысла проставлять картинки другого качества)

2022-06-08 06:08 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-06-08 06:29 UTC, MarMarIvanova commented on 06-lection4/02-background-image/background-image.css
> +  @media (min-width: 768px) {
не поняла замечания
По заданию: "Воспользоваться нужно способом вставки картинки через `background-image` и медиа-запросами". 
В зависимости от размеров экрана грузим разные картинки, разве нет?
![image](https://user-images.githubusercontent.com/85867526/172544687-345fe1a5-9396-48c3-a35f-b1f99fad0c11.png)

2022-06-08 17:25 UTC, GSemikozov commented on 06-lection4/02-background-image/background-image.css
> +  @media (min-width: 768px) {
ой, а откуда это описание? в задаче вот так:
<img width="1029" alt="Screenshot 2022-06-08 at 20 23 36" src="https://user-images.githubusercontent.com/6191270/172679004-7636595b-30cd-456d-bcd1-085eefbca503.png">

и насчет вопроса - пойдет от обратного: если размер аватара всегда 102x102, то будет ли иметь значение какого размера картинку будет грузить при разных разрешениях? Скорее, обратный эффект - где достаточно маленькой картинки, мы грузим большую, что плохо для производительности.

2022-06-08 18:03 UTC, MarMarIvanova commented on 06-lection4/02-background-image/background-image.css
> +  @media (min-width: 768px) {
это задача background-image, у нее в readme такое описане) 
![image](https://user-images.githubusercontent.com/85867526/172686014-3f34c3d8-6f3d-43c4-967f-49d4c2d06dbf.png)

2022-06-09 15:42 UTC, GSemikozov approved these changes

2022-06-09 15:42 UTC, GSemikozov commented on 06-lection4/02-background-image/background-image.css
> +  @media (min-width: 768px) {
да, понятно)
просто имя блока .avatar сбило с толку))

2022-06-09 15:42 UTC, merged