03-lection1
js-tasks-ru/htmlcss-20220519_mivanova pull request #3
Opened 2022-05-24 11:27 UTC by MarMarIvanova

2022-05-24 11:28 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-05-24 18:50 UTC, GSemikozov requested changes

2022-05-24 18:50 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    font-style: normal;
не хватает font-family

2022-05-24 18:50 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    width: 189px;
ширину лучше жестко не фиксировать - самый простой кейс когда верстка ломается, это если добавить длинный текст

2022-05-24 18:50 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    width: 189px;
не хватает внутренних отступов

2022-05-24 18:50 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    font-weight: 400;
здесь тоже не хватает font-family, и здесь он уже другой)

2022-05-24 18:50 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    width: 730px;
жестко не фиксируем, растягиваться все равно будет по родителю. В крайнем случае можно использовать мягкое ограничение через max-width

2022-05-24 18:50 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion__summary .marker {
по БЭМ - просто .accordion__arrow

2022-05-24 18:50 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion__details[open] .marker {
и тут

2022-05-24 18:50 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +details > summary {
если это глобальные / общие стили сброса, тогда их надо перенести например в normalize. Если это сброс в рамках компонента - тогда нужно оформить через БЭМ-классы

2022-05-24 18:50 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    float: right;
ой, про флоаты забываем как про страшный сон) если пока на примете нет других вариантов, то просто скрываем стрелку, а чуть позже сделаем как надо

2022-05-24 18:50 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +* {
если это глобальные стили - то в main.css, если только для компонента - то задаем на уровне .accordion

2022-05-24 18:50 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +* {
универсальный селектор здесь не нужно использовать, эти свойства и так наследуемые + мы будем использовать как минимум 3 разных шрифта на проекте

2022-05-24 18:50 UTC, GSemikozov commented on 03-lection1/02-accordion/index.html
> +    <body class="accordion" style="padding: 10px;">
чтобы удобнее было переиспользовать, лучше оформить через div

2022-05-24 18:50 UTC, GSemikozov commented on components/conteiner/conteiner.css
> +    max-width: 1440px;
1110

2022-05-24 18:50 UTC, GSemikozov commented on components/footer/footer.css
> +    width: 640px;
max-width

2022-05-25 05:09 UTC, MarMarIvanova commented on 03-lection1/01-button/button.css
> +    width: 189px;
Из-за того, что отступы не одинаковы, подумала, что как раз с помощью width и задается ширина кнопки, а не отступами) 
<img width="214" alt="image" src="https://user-images.githubusercontent.com/85867526/170184021-f676fc6c-b9bb-456d-b138-df23c269bcf0.png">
<img width="191" alt="image" src="https://user-images.githubusercontent.com/85867526/170184065-fb2d91b8-0f30-4a67-bab3-842d64dee9b9.png">
Каждому типу кнопки свои отступы назначить, как на макете?

2022-05-25 05:14 UTC, MarMarIvanova commented on 03-lection1/02-accordion/accordion.css
> +    font-weight: 400;
в accordeon.css ниже:
* {
    font-family: 'Inter', sans-serif;
    font-style: normal;
}
кажется, этого должно было хватить, но я перенесу выше, в .accordion

2022-05-25 06:20 UTC, MarMarIvanova commented on 03-lection1/02-accordion/accordion.css
> +details > summary {
перенесла в normalize

2022-05-25 09:31 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    width: 189px;
сверху-снизу - да, а вот слева-справа должны быть общие для всех, советую брать 15px

2022-05-25 09:33 UTC, GSemikozov requested changes

2022-05-25 09:33 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +* {
все еще актуально

2022-05-25 09:33 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    font-weight: 400;
да, ниже - ошибка, не используем `*`

2022-05-25 10:44 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-05-26 16:37 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-05-27 09:43 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-05-27 18:33 UTC, GSemikozov requested changes

2022-05-27 18:33 UTC, GSemikozov commented on components/footer/footer.css
> +.footer_header {
элементы - через 2 нижних подчеркивания

2022-05-27 18:33 UTC, GSemikozov commented on components/footer/footer.css
> +.footer_text {
и тут

2022-05-27 18:33 UTC, GSemikozov commented on components/footer/footer.css
> +.footer_header {
.footer__title

2022-05-27 18:47 UTC, GSemikozov approved these changes

2022-05-27 18:47 UTC, merged