modal
js-tasks-ru/htmlcss-20220519_mivanova pull request #9
Opened 2022-06-02 10:50 UTC by MarMarIvanova

2022-06-02 10:51 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-06-02 15:36 UTC, GSemikozov requested changes

2022-06-02 15:36 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.modal__conteiner {
а вот это уже лишнее - кнопка вызова модалки это не часть компонента Модалка )

2022-06-02 15:36 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    display: none;
открываться будет не элемент модалки, а весь блок .modal

2022-06-02 15:36 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    height: 100%;
не хватает позиционирования

2022-06-03 06:27 UTC, MarMarIvanova commented on 05-lection3/02-modal/modal.css
> +.modal__conteiner {
я могу добавить просто conteiner, не как часть модалки, а отдельным классом, чтобы выровнять кнопку по центру экрана?

2022-06-03 06:38 UTC, MarMarIvanova commented on 05-lection3/02-modal/modal.css
> +    height: 100%;
можно пояснить, а зачем здесь позиционирование? сейчас у меня modal выглядит так: 
.modal {
    display: none;
}
Это просто блок с модалкой, который становится display: block при клике на кнопку. Появляется он справа и занимает весь экран.

2022-06-05 10:45 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.modal__conteiner {
да, конечно, и если это просто вспомогательные стили и они нигде не переиспользуются - то такие стили лучше задавать в теге style внутри head хтмл страницы с решением

2022-06-05 10:50 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    height: 100%;
появляется от вроде как без проблем только сейчас, пока нет другого контента. Но - а что если попробовать встроить такую модалку на Главную?
Если эксперимент удастся, тогда продолжим обсуждение)

2022-06-06 06:51 UTC, MarMarIvanova commented on 05-lection3/02-modal/modal.css
> +    height: 100%;
добавила позиционирование

2022-06-06 14:04 UTC, GSemikozov requested changes

2022-06-06 14:04 UTC, GSemikozov commented on 05-lection3/02-modal/index.html
> +        <div class="modal__conteiner">
вот здесь должен быть блок .container, но ни в коем случае не элемент модалки вне своего родителя)

2022-06-06 14:04 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.conteiner {
стили для container + body - вспомогательные, их можно добавить в теге style хтмл страницы с решением, и точно не в файле стилей компонента

2022-06-07 06:14 UTC, MarMarIvanova commented on 05-lection3/02-modal/index.html
> +        <div class="modal__conteiner">
поняла!)

2022-06-07 17:55 UTC, GSemikozov requested changes

2022-06-07 17:55 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    left: 50%;
неа)
весь блок растягивается на 100% ширины и высоты, без ограничения размеров, фон через hsla

2022-06-07 17:55 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    position: fixed;
а вот здесь - фиксед уже не надо, можно например абсолют

2022-06-07 17:55 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.modal__conteiner {
кажется лишний элемент

2022-06-07 17:55 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    position: relative;
absolute; top: 16px; right: 16px (значения ставим из дизайна)

2022-06-09 15:41 UTC, GSemikozov approved these changes

2022-06-09 15:41 UTC, merged